@url_dev = http://localhost:3055/v1/api/cart

### create cart
POST {{url_dev}}
Content-Type: application/json
x-api-key: abcxyz
x-client-id: 64cf6706365c514ee5e11dd2
authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2NGNmNjcwNjM2NWM1MTRlZTVlMTFkZDIiLCJlbWFpbCI6InNob3Bqc0BnbWFpbC5jb20iLCJpYXQiOjE2OTE1NzMwMzAsImV4cCI6MTY5MTc0NTgzMH0.hBt3LCnlQMIrHwSL6ErOfHqsZC3z-7xuBmPmttiDEMc

{
  "userId": 1001,
  "product": {
    "productId": "64d3606aa8940382f089f344",
    "shopId": "64cf6706365c514ee5e11dd2",
    "quantity": 4,
    "name": "New Jeans 2",
    "price": 100
  }
}

### delete cart item
DELETE {{url_dev}}
Content-Type: application/json
x-api-key: abcxyz
x-client-id: 64cf6706365c514ee5e11dd2
authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2NGNmNjcwNjM2NWM1MTRlZTVlMTFkZDIiLCJlbWFpbCI6InNob3Bqc0BnbWFpbC5jb20iLCJpYXQiOjE2OTE1NzMwMzAsImV4cCI6MTY5MTc0NTgzMH0.hBt3LCnlQMIrHwSL6ErOfHqsZC3z-7xuBmPmttiDEMc

{
  "userId": 1001,
  "productId": "64d3606aa8940382f089f344"
}

### get list to cart
GET {{url_dev}}?userId=1001
x-api-key: abcxyz


### update cart
POST {{url_dev}}
Content-Type: application/json
x-api-key: abcxyz
x-client-id: 64cf6706365c514ee5e11dd2
authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2NGNmNjcwNjM2NWM1MTRlZTVlMTFkZDIiLCJlbWFpbCI6InNob3Bqc0BnbWFpbC5jb20iLCJpYXQiOjE2OTE1NzMwMzAsImV4cCI6MTY5MTc0NTgzMH0.hBt3LCnlQMIrHwSL6ErOfHqsZC3z-7xuBmPmttiDEMc

{
  "userId": 1001,
  "shop_order_ids": [
    {
      "shopId": "64cf6706365c514ee5e11dd2",
      "item_products":[
        {
          "quantity": 2,
          "price": 124,
          "shopId": "64cf6706365c514ee5e11dd2",
          "old_quantity": 4,
          "productId": "64d3606aa8940382f089f344"
        }
      ],
      "version": 2000
    }
  ]
}