@url_dev = http://localhost:3055/v1/api/cart

### create cart
POST {{url_dev}}
Content-Type: application/json
x-api-key: abcxyz
x-client-id: 64cf6706365c514ee5e11dd2
authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2NGNmNjcwNjM2NWM1MTRlZTVlMTFkZDIiLCJlbWFpbCI6InNob3Bqc0BnbWFpbC5jb20iLCJpYXQiOjE2OTIwOTMxMTgsImV4cCI6MTY5MjI2NTkxOH0.3_HKZ3LBI6TGvr0TIqzFWZn2nIq3SSKqziQ8O64NV20

{
  "userId": 1001,
  "product": {
    "productId": "64db4a215abd09c10fea8ad4",
    "shopId": "64db49f25abd09c10fea8acf",
    "quantity": 10,
    "name": "New Product shop 2",
    "price": 20000
  }
}

### delete cart item
DELETE {{url_dev}}
Content-Type: application/json
x-api-key: abcxyz
x-client-id: 64cf6706365c514ee5e11dd2
authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2NGNmNjcwNjM2NWM1MTRlZTVlMTFkZDIiLCJlbWFpbCI6InNob3Bqc0BnbWFpbC5jb20iLCJpYXQiOjE2OTE1NzMwMzAsImV4cCI6MTY5MTc0NTgzMH0.hBt3LCnlQMIrHwSL6ErOfHqsZC3z-7xuBmPmttiDEMc

{
  "userId": 1001,
  "productId": "64d3606aa8940382f089f344"
}

### get list to cart
GET {{url_dev}}?userId=1001
x-api-key: abcxyz


### update cart
POST {{url_dev}}/update
Content-Type: application/json
x-api-key: abcxyz
x-client-id: 64cf6706365c514ee5e11dd2
authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2NGNmNjcwNjM2NWM1MTRlZTVlMTFkZDIiLCJlbWFpbCI6InNob3Bqc0BnbWFpbC5jb20iLCJpYXQiOjE2OTE1NzMwMzAsImV4cCI6MTY5MTc0NTgzMH0.hBt3LCnlQMIrHwSL6ErOfHqsZC3z-7xuBmPmttiDEMc

{
  "userId": 1001,
  "shop_order_ids": [
    {
      "shopId": "64cf6706365c514ee5e11dd2",
      "item_products":[
        {
          "quantity": 5,
          "price": 124,
          "shopId": "64cf6706365c514ee5e11dd2",
          "old_quantity": 2,
          "productId": "64d3606aa8940382f089f344"
        }
      ],
      "version": 2000
    }
  ]
}