@url_dev = http://localhost:3055/v1/api/discount

### create discount
POST {{url_dev}}
Content-Type: application/json
x-api-key: abcxyz
x-client-id: 64cf6706365c514ee5e11dd2
authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2NGNmNjcwNjM2NWM1MTRlZTVlMTFkZDIiLCJlbWFpbCI6InNob3Bqc0BnbWFpbC5jb20iLCJpYXQiOjE2OTIwOTMxMTgsImV4cCI6MTY5MjI2NTkxOH0.3_HKZ3LBI6TGvr0TIqzFWZn2nIq3SSKqziQ8O64NV20

{
  "name": "name percentage sp 2 shop 2",
  "description": "description",
  "type": "percentage",
  "value": 10,
  "maxValue": 30000,
  "code": "SHOP-1133",
  "startDate": "2023-11-10 15:43:00",
  "endDate": "2023-11-15 15:43:00",
  "isActive":true,
  "minOrderValue": 200000,
  "productIds": ["64db4a215abd09c10fea8ad4"],
  "appliesTo": "specific",
  "maxUses": 100,
  "usesCount": 0,
  "maxUsesPerUser": 1,
  "usersUsed": []
}

### get all discount with products
GET {{url_dev}}/listProductCode?code=SHOP-1122&shopId=64cf6706365c514ee5e11dd2&limit=50&page=1
x-api-key: abcxyz

### get all discount by shop
GET {{url_dev}}?limit=50&page=1
x-api-key: abcxyz
x-client-id: 64cf6706365c514ee5e11dd2
authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2NGNmNjcwNjM2NWM1MTRlZTVlMTFkZDIiLCJlbWFpbCI6InNob3Bqc0BnbWFpbC5jb20iLCJpYXQiOjE2OTE4MjQ1NzMsImV4cCI6MTY5MTk5NzM3M30.Ua5ofWx9m3GcGpzwflGYpUY7F9cuRcan_eEaT9GIOjg

### get discount amount
POST {{url_dev}}/amount
Content-Type: application/json
x-api-key: abcxyz

{
  "codeId": "SHOP-1133",
  "userId": 2,
  "shopId": "64cf6706365c514ee5e11dd2",
  "products": [{
    "productId": "64d3606aa8940382f089f344",
    "quantity": 5,
    "price": 120000
  }]
}